controller:
  # Enable the use of Kubernetes agent pods
  JCasC:
    configScripts:
      agent-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                namespace: "infra"
                templates:
                  - name: "custom-agent"
                    label: "custom"
                    containers:
                      - name: "jnlp"
                        image: "rafaritter44/jenkins-agent"
                        ttyEnabled: true

  # RBAC setup so the controller can manage agents
  rbac:
    create: true

  # ServiceAccount used by controller with cluster-wide permissions
  serviceAccount:
    create: true
    name: jenkins

  # RBAC rules to allow cross-namespace deployments (to 'apps')
  additionalRules:
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "watch", "list", "create", "update", "delete"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "watch", "list", "create", "update", "delete"]

agent:
  # Disable default agent image to avoid pulling the wrong one
  enabled: false