apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: apps
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}